export const VALUE_MODEL = {
  enabled: true,
  featureNames: [
    'win1_diff',
    'win2_diff',
    'live5_diff',
    'charge5_diff',
    'live4_diff',
    'charge4_diff',
    'double_four_diff',
    'four_three_diff',
    'double_three_diff',
    'live3_diff',
    'sleep3_diff',
    'attack_points_diff',
    'defense_points_diff',
    'live2_diff',
    'sleep2_diff',
    'initiative_diff',
    'connectivity_diff',
    'shape_balance_diff',
    'stone_count_diff',
    'center_control_diff',
    'frontier_diff',
    'max_chain_diff',
    'group_count_diff',
  ],
  weights: [
    3.4, 2.6, 2.1, 1.1, 1.8, 0.9, 1.4, 1.1, 0.8, 0.5, 0.3, 0.1, 0.08,
    0.15, 0.08, 0.25, 0.08, 0.06, 0.05, 0.06, 0.06, 0.12, 0.03,
  ],
  bias: 0,
  trainedAt: null as string | null,
  samples: 0,
  epochs: 0,
};
